version: '3.8'
services:
  mplat-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mplat-server
    restart: always
    ports:
      - 6086:3001
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
